In [1]:
import numpy as np

In [2]:
array1 = np.arange(1,10).reshape(3,3)
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
array2 = np.arange(10,19).reshape(3,3)
array2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [4]:
np.concatenate((array1,array2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [5]:
np.concatenate((array1,array2), axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [6]:
list1 = np.split(array1,3)
list1

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [7]:
list2 = np.split(array1,3,axis=1)
list2

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]