In [1]:
import numpy as np

In [2]:
array1 = [[1,1,1],[1,1,1],[1,1,1]]
array1

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [4]:
array2 = np.ones(5)
array2

array([1., 1., 1., 1., 1.])

In [5]:
array3 = np.ones((3,3))
array3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
array4 = np.ones((3,3), dtype=int)    ##by default dtype is float , we have to specify if we need different data type
array4

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
array5 = np.zeros((5,5), dtype=int)
array5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
array6 = np.zeros((5,5), dtype=bool)
array6

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [14]:
array7= np.zeros((5,5), dtype=str)
array7

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')