In [2]:
import numpy as np

In [6]:
np.random.random(1)

array([0.81473345])

In [3]:

np.random.random((3,3))

array([[0.88991069, 0.45796406, 0.63290956],
       [0.73006541, 0.917318  , 0.44433427],
       [0.57518945, 0.31716296, 0.41118302]])

In [11]:
np.random.randint(1,5)

1

In [5]:
np.random.randint(1,5,(5,6))      

array([[2, 3, 4, 3, 4, 1],
       [3, 4, 3, 4, 4, 1],
       [2, 2, 1, 3, 3, 3],
       [1, 2, 1, 2, 4, 1],
       [4, 3, 4, 3, 1, 4]])

In [6]:
np.random.randint(4,7,(3,5,6))      

array([[[4, 5, 5, 5, 4, 6],
        [5, 6, 4, 5, 5, 6],
        [5, 6, 4, 6, 5, 4],
        [4, 4, 5, 4, 5, 6],
        [5, 4, 5, 4, 4, 6]],

       [[6, 5, 6, 6, 6, 4],
        [4, 6, 4, 4, 6, 4],
        [5, 6, 6, 4, 4, 5],
        [6, 6, 4, 4, 5, 6],
        [4, 4, 5, 6, 4, 4]],

       [[5, 5, 6, 4, 4, 4],
        [6, 6, 4, 4, 4, 6],
        [4, 6, 4, 6, 5, 4],
        [5, 6, 5, 5, 4, 5],
        [4, 4, 6, 6, 5, 6]]])

In [17]:
np.random.seed(10)
np.random.randint(1,5)



2

In [8]:
np.random.seed(10)
np.random.randint(1,5)

2

In [19]:
x = [1,2,3,4,5]
np.random.choice(x)

1